from defines import *
from graph_canvas import *
from USB_device import *
from message_decoder import *

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(586, 507)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.qMainWindow = QtWidgets.QWidget(MainWindow)
        self.qMainWindow.setObjectName("qMainWindow")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.qMainWindow)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.qMainWindowGLayout1 = QtWidgets.QGridLayout()
        self.qMainWindowGLayout1.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.qMainWindowGLayout1.setObjectName("qMainWindowGLayout1")
        self.qTerminalSendCheckBox = QtWidgets.QCheckBox(self.qMainWindow)
        self.qTerminalSendCheckBox.setObjectName("qTerminalSendCheckBox")
        self.qMainWindowGLayout1.addWidget(self.qTerminalSendCheckBox, 0, 0, 1, 1)
        self.qConnectionLabel = QtWidgets.QLabel(self.qMainWindow)
        self.qConnectionLabel.setAutoFillBackground(False)
        self.qConnectionLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
            "background-color: rgb(255, 0, 0);\n"
            "border-color: rgb(255, 255, 255);")
        self.qConnectionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.qConnectionLabel.setObjectName("qConnectionLabel")
        self.qMainWindowGLayout1.addWidget(self.qConnectionLabel, 3, 0, 1, 1)
        self.qRawDisCheckBox = QtWidgets.QCheckBox(self.qMainWindow)
        self.qRawDisCheckBox.setObjectName("qRawDisCheckBox")
        self.qMainWindowGLayout1.addWidget(self.qRawDisCheckBox, 1, 0, 1, 1)
        self.qConstantLabelConst = QtWidgets.QLabel(self.qMainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qConstantLabelConst.sizePolicy().hasHeightForWidth())
        self.qConstantLabelConst.setSizePolicy(sizePolicy)
        self.qConstantLabelConst.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qConstantLabelConst.setObjectName("qConstantLabelConst")
        self.qMainWindowGLayout1.addWidget(self.qConstantLabelConst, 0, 1, 1, 1)
        self.qStartButton = QtWidgets.QPushButton(self.qMainWindow)
        self.qStartButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qStartButton.sizePolicy().hasHeightForWidth())
        self.qStartButton.setSizePolicy(sizePolicy)
        self.qStartButton.setMinimumSize(QtCore.QSize(100, 0))
        self.qStartButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.qStartButton.setStyleSheet("color: rgb(0, 0, 0);\n"
            "alternate-background-color: rgb(0, 170, 0);\n"
            "background-color: rgb(0, 255, 0);\n"
            "border-color: rgb(0, 0, 0);")
        self.qStartButton.setObjectName("qStartButton")
        self.qMainWindowGLayout1.addWidget(self.qStartButton, 5, 2, 1, 1)
        self.qLabelRunTime = QtWidgets.QLabel(self.qMainWindow)
        self.qLabelRunTime.setMinimumSize(QtCore.QSize(100, 0))
        self.qLabelRunTime.setMaximumSize(QtCore.QSize(200, 16777215))
        self.qLabelRunTime.setObjectName("qLabelRunTime")
        self.qMainWindowGLayout1.addWidget(self.qLabelRunTime, 1, 2, 1, 1)
        self.qFileNameLineEdi = QtWidgets.QLineEdit(self.qMainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qFileNameLineEdi.sizePolicy().hasHeightForWidth())
        self.qFileNameLineEdi.setSizePolicy(sizePolicy)
        self.qFileNameLineEdi.setObjectName("qFileNameLineEdi")
        self.qMainWindowGLayout1.addWidget(self.qFileNameLineEdi, 3, 1, 1, 1)
        self.qPauseButton = QtWidgets.QPushButton(self.qMainWindow)
        self.qPauseButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qPauseButton.sizePolicy().hasHeightForWidth())
        self.qPauseButton.setSizePolicy(sizePolicy)
        self.qPauseButton.setMinimumSize(QtCore.QSize(100, 0))
        self.qPauseButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.qPauseButton.setMouseTracking(False)
        self.qPauseButton.setStyleSheet("background-color: rgb(255, 255, 0);\n"
            "color: rgb(0, 0, 0);\n"
            "border-color: rgb(0, 0, 0);")
        self.qPauseButton.setObjectName("qPauseButton")
        self.qMainWindowGLayout1.addWidget(self.qPauseButton, 5, 1, 1, 1)
        self.qConstModeComBox = QtWidgets.QComboBox(self.qMainWindow)
        self.qConstModeComBox.setObjectName("qConstModeComBox")
        self.qConstModeComBox.addItem("")
        self.qConstModeComBox.addItem("")
        self.qConstModeComBox.addItem("")
        self.qMainWindowGLayout1.addWidget(self.qConstModeComBox, 0, 2, 1, 1)
        self.qConstLabelRun = QtWidgets.QLabel(self.qMainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qConstLabelRun.sizePolicy().hasHeightForWidth())
        self.qConstLabelRun.setSizePolicy(sizePolicy)
        self.qConstLabelRun.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qConstLabelRun.setObjectName("qConstLabelRun")
        self.qMainWindowGLayout1.addWidget(self.qConstLabelRun, 1, 1, 1, 1)
        self.qConstLabelFile = QtWidgets.QLabel(self.qMainWindow)
        self.qConstLabelFile.setMaximumSize(QtCore.QSize(200, 16777215))
        self.qConstLabelFile.setObjectName("qConstLabelFile")
        self.qMainWindowGLayout1.addWidget(self.qConstLabelFile, 3, 2, 1, 1)
        self.qStopButton = QtWidgets.QPushButton(self.qMainWindow)
        self.qStopButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qStopButton.sizePolicy().hasHeightForWidth())
        self.qStopButton.setSizePolicy(sizePolicy)
        self.qStopButton.setMinimumSize(QtCore.QSize(110, 0))
        self.qStopButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.qStopButton.setStyleSheet("border-color: rgb(0, 0, 0);\n"
            "color: rgb(255, 255, 255);\n"
            "background-color: rgb(255, 0, 0);")
        self.qStopButton.setObjectName("qStopButton")
        self.qMainWindowGLayout1.addWidget(self.qStopButton, 5, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.qMainWindowGLayout1.addItem(spacerItem, 6, 0, 1, 1)
        self.gridLayout_2.addLayout(self.qMainWindowGLayout1, 4, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.qMainWindow)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 3, 0, 1, 1)
        self.aUpdateLabel = QtWidgets.QLabel(self.qMainWindow)
        self.aUpdateLabel.setText("")
        self.aUpdateLabel.setObjectName("aUpdateLabel")
        self.gridLayout_2.addWidget(self.aUpdateLabel, 2, 0, 1, 1)
        self.qMainWindowVLayout1 = QtWidgets.QVBoxLayout()
        self.qMainWindowVLayout1.setObjectName("qMainWindowVLayout1")
        self.qMainTabWidget = QtWidgets.QTabWidget(self.qMainWindow)
        self.qMainTabWidget.setMinimumSize(QtCore.QSize(300, 200))
        self.qMainTabWidget.setMaximumSize(QtCore.QSize(400, 16777215))
        self.qMainTabWidget.setObjectName("qMainTabWidget")
        self.qMainTempSetWidget = QtWidgets.QWidget()
        self.qMainTempSetWidget.setObjectName("qMainTempSetWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.qMainTempSetWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.qStaticLabelUnitT = QtWidgets.QLabel(self.qMainTempSetWidget)
        self.qStaticLabelUnitT.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qStaticLabelUnitT.setObjectName("qStaticLabelUnitT")
        self.horizontalLayout.addWidget(self.qStaticLabelUnitT)
        self.qTemUnitComBox = QtWidgets.QComboBox(self.qMainTempSetWidget)
        self.qTemUnitComBox.setMinimumSize(QtCore.QSize(20, 0))
        self.qTemUnitComBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.qTemUnitComBox.setObjectName("qTemUnitComBox")
        self.qTemUnitComBox.addItem("")
        self.qTemUnitComBox.addItem("")
        self.horizontalLayout.addWidget(self.qTemUnitComBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.qTempMaxSpin = QtWidgets.QSpinBox(self.qMainTempSetWidget)
        self.qTempMaxSpin.setAlignment(QtCore.Qt.AlignCenter)
        self.qTempMaxSpin.setMinimum(-5)
        self.qTempMaxSpin.setMaximum(85)
        self.qTempMaxSpin.setProperty("value", 80)
        self.qTempMaxSpin.setObjectName("qTempMaxSpin")
        self.gridLayout_5.addWidget(self.qTempMaxSpin, 2, 2, 1, 1)
        self.qStaticLabelTmax = QtWidgets.QLabel(self.qMainTempSetWidget)
        self.qStaticLabelTmax.setAlignment(QtCore.Qt.AlignCenter)
        self.qStaticLabelTmax.setObjectName("qStaticLabelTmax")
        self.gridLayout_5.addWidget(self.qStaticLabelTmax, 0, 2, 1, 1)
        self.qTempMinDial = QtWidgets.QDial(self.qMainTempSetWidget)
        self.qTempMinDial.setMinimum(-5)
        self.qTempMinDial.setMaximum(85)
        self.qTempMinDial.setWrapping(False)
        self.qTempMinDial.setNotchesVisible(True)
        self.qTempMinDial.setObjectName("qTempMinDial")
        self.gridLayout_5.addWidget(self.qTempMinDial, 1, 0, 1, 1)
        self.qTempStepSpin = QtWidgets.QSpinBox(self.qMainTempSetWidget)
        self.qTempStepSpin.setAlignment(QtCore.Qt.AlignCenter)
        self.qTempStepSpin.setMinimum(1)
        self.qTempStepSpin.setMaximum(90)
        self.qTempStepSpin.setSingleStep(5)
        self.qTempStepSpin.setProperty("value", 20)
        self.qTempStepSpin.setObjectName("qTempStepSpin")
        self.gridLayout_5.addWidget(self.qTempStepSpin, 2, 1, 1, 1)
        self.qStaticLabelTMin = QtWidgets.QLabel(self.qMainTempSetWidget)
        self.qStaticLabelTMin.setAlignment(QtCore.Qt.AlignCenter)
        self.qStaticLabelTMin.setObjectName("qStaticLabelTMin")
        self.gridLayout_5.addWidget(self.qStaticLabelTMin, 0, 0, 1, 1)
        self.qStaticLabelTstep = QtWidgets.QLabel(self.qMainTempSetWidget)
        self.qStaticLabelTstep.setAlignment(QtCore.Qt.AlignCenter)
        self.qStaticLabelTstep.setObjectName("qStaticLabelTstep")
        self.gridLayout_5.addWidget(self.qStaticLabelTstep, 0, 1, 1, 1)
        self.qTempMinSpin = QtWidgets.QSpinBox(self.qMainTempSetWidget)
        self.qTempMinSpin.setAlignment(QtCore.Qt.AlignCenter)
        self.qTempMinSpin.setMinimum(-5)
        self.qTempMinSpin.setMaximum(80)
        self.qTempMinSpin.setObjectName("qTempMinSpin")
        self.gridLayout_5.addWidget(self.qTempMinSpin, 2, 0, 1, 1)
        self.qTempMaxDial = QtWidgets.QDial(self.qMainTempSetWidget)
        self.qTempMaxDial.setMinimum(-5)
        self.qTempMaxDial.setMaximum(85)
        self.qTempMaxDial.setProperty("value", 80)
        self.qTempMaxDial.setNotchesVisible(True)
        self.qTempMaxDial.setObjectName("qTempMaxDial")
        self.gridLayout_5.addWidget(self.qTempMaxDial, 1, 2, 1, 1)
        self.qTempStepDial = QtWidgets.QDial(self.qMainTempSetWidget)
        self.qTempStepDial.setMinimum(1)
        self.qTempStepDial.setMaximum(90)
        self.qTempStepDial.setSingleStep(5)
        self.qTempStepDial.setProperty("value", 20)
        self.qTempStepDial.setNotchesVisible(True)
        self.qTempStepDial.setObjectName("qTempStepDial")
        self.gridLayout_5.addWidget(self.qTempStepDial, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.qMainTabWidget.addTab(self.qMainTempSetWidget, "")
        self.qMainVoltSetWidget = QtWidgets.QWidget()
        self.qMainVoltSetWidget.setObjectName("qMainVoltSetWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.qMainVoltSetWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.qStaticLabelVmax = QtWidgets.QLabel(self.qMainVoltSetWidget)
        self.qStaticLabelVmax.setAlignment(QtCore.Qt.AlignCenter)
        self.qStaticLabelVmax.setObjectName("qStaticLabelVmax")
        self.gridLayout_7.addWidget(self.qStaticLabelVmax, 0, 2, 1, 1)
        self.qStaticLabelVstep = QtWidgets.QLabel(self.qMainVoltSetWidget)
        self.qStaticLabelVstep.setAlignment(QtCore.Qt.AlignCenter)
        self.qStaticLabelVstep.setObjectName("qStaticLabelVstep")
        self.gridLayout_7.addWidget(self.qStaticLabelVstep, 0, 1, 1, 1)
        self.qStaticLabelVMin = QtWidgets.QLabel(self.qMainVoltSetWidget)
        self.qStaticLabelVMin.setAlignment(QtCore.Qt.AlignCenter)
        self.qStaticLabelVMin.setObjectName("qStaticLabelVMin")
        self.gridLayout_7.addWidget(self.qStaticLabelVMin, 0, 0, 1, 1)
        self.qVMaxDial = QtWidgets.QDial(self.qMainVoltSetWidget)
        self.qVMaxDial.setMinimum(-5)
        self.qVMaxDial.setMaximum(85)
        self.qVMaxDial.setProperty("value", 80)
        self.qVMaxDial.setNotchesVisible(True)
        self.qVMaxDial.setObjectName("qVMaxDial")
        self.gridLayout_7.addWidget(self.qVMaxDial, 2, 2, 1, 1)
        self.qVMaxUnitComBox = QtWidgets.QComboBox(self.qMainVoltSetWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qVMaxUnitComBox.sizePolicy().hasHeightForWidth())
        self.qVMaxUnitComBox.setSizePolicy(sizePolicy)
        self.qVMaxUnitComBox.setMinimumSize(QtCore.QSize(0, 0))
        self.qVMaxUnitComBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.qVMaxUnitComBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.qVMaxUnitComBox.setObjectName("qVMaxUnitComBox")
        self.qVMaxUnitComBox.addItem("")
        self.qVMaxUnitComBox.addItem("")
        self.gridLayout_7.addWidget(self.qVMaxUnitComBox, 4, 1, 1, 1)
        self.qVMinDial = QtWidgets.QDial(self.qMainVoltSetWidget)
        self.qVMinDial.setMinimum(-5)
        self.qVMinDial.setMaximum(85)
        self.qVMinDial.setWrapping(False)
        self.qVMinDial.setNotchesVisible(True)
        self.qVMinDial.setObjectName("qVMinDial")
        self.gridLayout_7.addWidget(self.qVMinDial, 2, 0, 1, 1)
        self.qVStepDial = QtWidgets.QDial(self.qMainVoltSetWidget)
        self.qVStepDial.setMinimum(1)
        self.qVStepDial.setMaximum(90)
        self.qVStepDial.setSingleStep(5)
        self.qVStepDial.setProperty("value", 20)
        self.qVStepDial.setNotchesVisible(True)
        self.qVStepDial.setObjectName("qVStepDial")
        self.gridLayout_7.addWidget(self.qVStepDial, 2, 1, 1, 1)
        self.qVMinUnitComBox = QtWidgets.QComboBox(self.qMainVoltSetWidget)
        self.qVMinUnitComBox.setMinimumSize(QtCore.QSize(0, 0))
        self.qVMinUnitComBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.qVMinUnitComBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.qVMinUnitComBox.setObjectName("qVMinUnitComBox")
        self.qVMinUnitComBox.addItem("")
        self.qVMinUnitComBox.addItem("")
        self.gridLayout_7.addWidget(self.qVMinUnitComBox, 4, 0, 1, 1)
        self.qVStepSpin = QtWidgets.QDoubleSpinBox(self.qMainVoltSetWidget)
        self.qVStepSpin.setAlignment(QtCore.Qt.AlignCenter)
        self.qVStepSpin.setObjectName("qVStepSpin")
        self.gridLayout_7.addWidget(self.qVStepSpin, 3, 1, 1, 1)
        self.qVMinSpin = QtWidgets.QDoubleSpinBox(self.qMainVoltSetWidget)
        self.qVMinSpin.setAlignment(QtCore.Qt.AlignCenter)
        self.qVMinSpin.setObjectName("qVMinSpin")
        self.gridLayout_7.addWidget(self.qVMinSpin, 3, 0, 1, 1)
        self.qVMaxUnitComBox_2 = QtWidgets.QComboBox(self.qMainVoltSetWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qVMaxUnitComBox_2.sizePolicy().hasHeightForWidth())
        self.qVMaxUnitComBox_2.setSizePolicy(sizePolicy)
        self.qVMaxUnitComBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.qVMaxUnitComBox_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.qVMaxUnitComBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.qVMaxUnitComBox_2.setEditable(False)
        self.qVMaxUnitComBox_2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.qVMaxUnitComBox_2.setObjectName("qVMaxUnitComBox_2")
        self.qVMaxUnitComBox_2.addItem("")
        self.qVMaxUnitComBox_2.addItem("")
        self.gridLayout_7.addWidget(self.qVMaxUnitComBox_2, 4, 2, 1, 1)
        self.qVMaxSpin = QtWidgets.QDoubleSpinBox(self.qMainVoltSetWidget)
        self.qVMaxSpin.setAlignment(QtCore.Qt.AlignCenter)
        self.qVMaxSpin.setObjectName("qVMaxSpin")
        self.gridLayout_7.addWidget(self.qVMaxSpin, 3, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_7)
        self.qMainTabWidget.addTab(self.qMainVoltSetWidget, "")
        self.qMainCurrentSetWidget = QtWidgets.QWidget()
        self.qMainCurrentSetWidget.setObjectName("qMainCurrentSetWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.qMainCurrentSetWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.qStaticLabelIstep = QtWidgets.QLabel(self.qMainCurrentSetWidget)
        self.qStaticLabelIstep.setAlignment(QtCore.Qt.AlignCenter)
        self.qStaticLabelIstep.setObjectName("qStaticLabelIstep")
        self.gridLayout_8.addWidget(self.qStaticLabelIstep, 0, 1, 1, 1)
        self.qStaticLabelImax = QtWidgets.QLabel(self.qMainCurrentSetWidget)
        self.qStaticLabelImax.setAlignment(QtCore.Qt.AlignCenter)
        self.qStaticLabelImax.setObjectName("qStaticLabelImax")
        self.gridLayout_8.addWidget(self.qStaticLabelImax, 0, 2, 1, 1)
        self.qStaticLabelIMin = QtWidgets.QLabel(self.qMainCurrentSetWidget)
        self.qStaticLabelIMin.setAlignment(QtCore.Qt.AlignCenter)
        self.qStaticLabelIMin.setObjectName("qStaticLabelIMin")
        self.gridLayout_8.addWidget(self.qStaticLabelIMin, 0, 0, 1, 1)
        self.qIStepSpin = QtWidgets.QDoubleSpinBox(self.qMainCurrentSetWidget)
        self.qIStepSpin.setAlignment(QtCore.Qt.AlignCenter)
        self.qIStepSpin.setObjectName("qIStepSpin")
        self.gridLayout_8.addWidget(self.qIStepSpin, 3, 1, 1, 1)
        self.qIStepDial = QtWidgets.QDial(self.qMainCurrentSetWidget)
        self.qIStepDial.setMinimum(1)
        self.qIStepDial.setMaximum(90)
        self.qIStepDial.setSingleStep(5)
        self.qIStepDial.setProperty("value", 20)
        self.qIStepDial.setNotchesVisible(True)
        self.qIStepDial.setObjectName("qIStepDial")
        self.gridLayout_8.addWidget(self.qIStepDial, 2, 1, 1, 1)
        self.qIMaxDial = QtWidgets.QDial(self.qMainCurrentSetWidget)
        self.qIMaxDial.setMinimum(-5)
        self.qIMaxDial.setMaximum(85)
        self.qIMaxDial.setProperty("value", 80)
        self.qIMaxDial.setNotchesVisible(True)
        self.qIMaxDial.setObjectName("qIMaxDial")
        self.gridLayout_8.addWidget(self.qIMaxDial, 2, 2, 1, 1)
        self.qIMaxSpin = QtWidgets.QDoubleSpinBox(self.qMainCurrentSetWidget)
        self.qIMaxSpin.setAlignment(QtCore.Qt.AlignCenter)
        self.qIMaxSpin.setObjectName("qIMaxSpin")
        self.gridLayout_8.addWidget(self.qIMaxSpin, 3, 2, 1, 1)
        self.qIMinDial = QtWidgets.QDial(self.qMainCurrentSetWidget)
        self.qIMinDial.setMinimum(-5)
        self.qIMinDial.setMaximum(85)
        self.qIMinDial.setWrapping(False)
        self.qIMinDial.setNotchesVisible(True)
        self.qIMinDial.setObjectName("qIMinDial")
        self.gridLayout_8.addWidget(self.qIMinDial, 2, 0, 1, 1)
        self.qStaticLabelPeltMax = QtWidgets.QLabel(self.qMainCurrentSetWidget)
        self.qStaticLabelPeltMax.setObjectName("qStaticLabelPeltMax")
        self.gridLayout_8.addWidget(self.qStaticLabelPeltMax, 0, 3, 1, 1)
        self.qIMinSpin = QtWidgets.QDoubleSpinBox(self.qMainCurrentSetWidget)
        self.qIMinSpin.setAlignment(QtCore.Qt.AlignCenter)
        self.qIMinSpin.setObjectName("qIMinSpin")
        self.gridLayout_8.addWidget(self.qIMinSpin, 3, 0, 1, 1)
        self.qIStepUnitComBox = QtWidgets.QComboBox(self.qMainCurrentSetWidget)
        self.qIStepUnitComBox.setObjectName("qIStepUnitComBox")
        self.qIStepUnitComBox.addItem("")
        self.qIStepUnitComBox.addItem("")
        self.gridLayout_8.addWidget(self.qIStepUnitComBox, 4, 1, 1, 1)
        self.qPeltIMaxSpin = QtWidgets.QDoubleSpinBox(self.qMainCurrentSetWidget)
        self.qPeltIMaxSpin.setAlignment(QtCore.Qt.AlignCenter)
        self.qPeltIMaxSpin.setObjectName("qPeltIMaxSpin")
        self.gridLayout_8.addWidget(self.qPeltIMaxSpin, 3, 3, 1, 1)
        self.qIMinUnitComBox = QtWidgets.QComboBox(self.qMainCurrentSetWidget)
        self.qIMinUnitComBox.setObjectName("qIMinUnitComBox")
        self.qIMinUnitComBox.addItem("")
        self.qIMinUnitComBox.addItem("")
        self.gridLayout_8.addWidget(self.qIMinUnitComBox, 4, 0, 1, 1)
        self.qPeltIMaxDial = QtWidgets.QDial(self.qMainCurrentSetWidget)
        self.qPeltIMaxDial.setNotchesVisible(True)
        self.qPeltIMaxDial.setObjectName("qPeltIMaxDial")
        self.gridLayout_8.addWidget(self.qPeltIMaxDial, 2, 3, 1, 1)
        self.qIMaxUnitComBox = QtWidgets.QComboBox(self.qMainCurrentSetWidget)
        self.qIMaxUnitComBox.setObjectName("qIMaxUnitComBox")
        self.qIMaxUnitComBox.addItem("")
        self.qIMaxUnitComBox.addItem("")
        self.gridLayout_8.addWidget(self.qIMaxUnitComBox, 4, 2, 1, 1)
        self.qStaticLabelA = QtWidgets.QLabel(self.qMainCurrentSetWidget)
        self.qStaticLabelA.setAlignment(QtCore.Qt.AlignCenter)
        self.qStaticLabelA.setObjectName("qStaticLabelA")
        self.gridLayout_8.addWidget(self.qStaticLabelA, 4, 3, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_8)
        self.qMainTabWidget.addTab(self.qMainCurrentSetWidget, "")
        self.qMainGraphSetWidget = QtWidgets.QWidget()
        self.qMainGraphSetWidget.setObjectName("qMainGraphSetWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.qMainGraphSetWidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.qMainGraphSetWidget)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout_6.addLayout(self.gridLayout_9)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_5.addLayout(self.gridLayout_6)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.qMainTabWidget.addTab(self.qMainGraphSetWidget, "")
        self.qMainWindowVLayout1.addWidget(self.qMainTabWidget)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.qDevVDisplayComBox = QtWidgets.QComboBox(self.qMainWindow)
        self.qDevVDisplayComBox.setMinimumSize(QtCore.QSize(50, 0))
        self.qDevVDisplayComBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.qDevVDisplayComBox.setObjectName("qDevVDisplayComBox")
        self.qDevVDisplayComBox.addItem("")
        self.qDevVDisplayComBox.addItem("")
        self.gridLayout_4.addWidget(self.qDevVDisplayComBox, 0, 2, 1, 1)
        self.qDevVDisplayLabel = QtWidgets.QLabel(self.qMainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qDevVDisplayLabel.sizePolicy().hasHeightForWidth())
        self.qDevVDisplayLabel.setSizePolicy(sizePolicy)
        self.qDevVDisplayLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.qDevVDisplayLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.qDevVDisplayLabel.setBaseSize(QtCore.QSize(150, 0))
        self.qDevVDisplayLabel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.qDevVDisplayLabel.setObjectName("qDevVDisplayLabel")
        self.gridLayout_4.addWidget(self.qDevVDisplayLabel, 0, 1, 1, 1)
        self.qStaticLabelDevT = QtWidgets.QLabel(self.qMainWindow)
        self.qStaticLabelDevT.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qStaticLabelDevT.setObjectName("qStaticLabelDevT")
        self.gridLayout_4.addWidget(self.qStaticLabelDevT, 3, 0, 1, 1)
        self.qDevADisplayLabel = QtWidgets.QLabel(self.qMainWindow)
        self.qDevADisplayLabel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.qDevADisplayLabel.setObjectName("qDevADisplayLabel")
        self.gridLayout_4.addWidget(self.qDevADisplayLabel, 1, 1, 1, 1)
        self.qStaticLabelDevA = QtWidgets.QLabel(self.qMainWindow)
        self.qStaticLabelDevA.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qStaticLabelDevA.setObjectName("qStaticLabelDevA")
        self.gridLayout_4.addWidget(self.qStaticLabelDevA, 1, 0, 1, 1)
        self.qStaticLabelDdevV = QtWidgets.QLabel(self.qMainWindow)
        self.qStaticLabelDdevV.setMinimumSize(QtCore.QSize(100, 0))
        self.qStaticLabelDdevV.setMaximumSize(QtCore.QSize(200, 16777215))
        self.qStaticLabelDdevV.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qStaticLabelDdevV.setObjectName("qStaticLabelDdevV")
        self.gridLayout_4.addWidget(self.qStaticLabelDdevV, 0, 0, 1, 1)
        self.qDevADisplayComBox = QtWidgets.QComboBox(self.qMainWindow)
        self.qDevADisplayComBox.setMinimumSize(QtCore.QSize(50, 0))
        self.qDevADisplayComBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.qDevADisplayComBox.setObjectName("qDevADisplayComBox")
        self.qDevADisplayComBox.addItem("")
        self.qDevADisplayComBox.addItem("")
        self.qDevADisplayComBox.addItem("")
        self.gridLayout_4.addWidget(self.qDevADisplayComBox, 1, 2, 1, 1)
        self.qStaticLabelPelA = QtWidgets.QLabel(self.qMainWindow)
        self.qStaticLabelPelA.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qStaticLabelPelA.setObjectName("qStaticLabelPelA")
        self.gridLayout_4.addWidget(self.qStaticLabelPelA, 2, 0, 1, 1)
        self.qPelADisplayComBox = QtWidgets.QComboBox(self.qMainWindow)
        self.qPelADisplayComBox.setMinimumSize(QtCore.QSize(50, 0))
        self.qPelADisplayComBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.qPelADisplayComBox.setObjectName("qPelADisplayComBox")
        self.qPelADisplayComBox.addItem("")
        self.qPelADisplayComBox.addItem("")
        self.gridLayout_4.addWidget(self.qPelADisplayComBox, 2, 2, 1, 1)
        self.qDevTDisplayComBox = QtWidgets.QComboBox(self.qMainWindow)
        self.qDevTDisplayComBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.qDevTDisplayComBox.setObjectName("qDevTDisplayComBox")
        self.qDevTDisplayComBox.addItem("")
        self.qDevTDisplayComBox.addItem("")
        self.gridLayout_4.addWidget(self.qDevTDisplayComBox, 3, 2, 1, 1)
        self.qPelADisplayLabel = QtWidgets.QLabel(self.qMainWindow)
        self.qPelADisplayLabel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.qPelADisplayLabel.setObjectName("qPelADisplayLabel")
        self.gridLayout_4.addWidget(self.qPelADisplayLabel, 2, 1, 1, 1)
        self.qDevTDisplayLabel = QtWidgets.QLabel(self.qMainWindow)
        self.qDevTDisplayLabel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.qDevTDisplayLabel.setObjectName("qDevTDisplayLabel")
        self.gridLayout_4.addWidget(self.qDevTDisplayLabel, 3, 1, 1, 1)
        self.qMainWindowVLayout1.addLayout(self.gridLayout_4)
        self.gridLayout_2.addLayout(self.qMainWindowVLayout1, 1, 0, 1, 1)
        self.qManualGridLayout = QtWidgets.QGridLayout()
        self.qManualGridLayout.setObjectName("qManualGridLayout")
        self.qManPWMDApplyButton = QtWidgets.QPushButton(self.qMainWindow)
        self.qManPWMDApplyButton.setObjectName("qManPWMDApplyButton")
        self.qManualGridLayout.addWidget(self.qManPWMDApplyButton, 2, 0, 1, 1)
        self.qManPWMDSpinBox = QtWidgets.QSpinBox(self.qMainWindow)
        self.qManPWMDSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.qManPWMDSpinBox.setMaximum(1000)
        self.qManPWMDSpinBox.setObjectName("qManPWMDSpinBox")
        self.qManualGridLayout.addWidget(self.qManPWMDSpinBox, 1, 0, 1, 1)
        self.qStaticLabelPWMFreq = QtWidgets.QLabel(self.qMainWindow)
        self.qStaticLabelPWMFreq.setObjectName("qStaticLabelPWMFreq")
        self.qManualGridLayout.addWidget(self.qStaticLabelPWMFreq, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.qManualGridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        self.gridLayout_2.addLayout(self.qManualGridLayout, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.qMainWindow)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 586, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuDevice = QtWidgets.QMenu(self.menubar)
        self.menuDevice.setObjectName("menuDevice")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.qGraphWidget = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qGraphWidget.sizePolicy().hasHeightForWidth())
        self.qGraphWidget.setSizePolicy(sizePolicy)
        self.qGraphWidget.setBaseSize(QtCore.QSize(463, 300))
        self.qGraphWidget.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.qGraphWidget.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.qGraphWidget.setObjectName("qGraphWidget")
        self.qGraphWidgetWindow = QtWidgets.QWidget()
        self.qGraphWidgetWindow.setObjectName("qGraphWidgetWindow")
        self.gridLayout = QtWidgets.QGridLayout(self.qGraphWidgetWindow)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.qGraphVLayout = QtWidgets.QVBoxLayout()
        self.qGraphVLayout.setObjectName("qGraphVLayout")
        self.gridLayout.addLayout(self.qGraphVLayout, 0, 1, 1, 1)
        self.qGraphWidget.setWidget(self.qGraphWidgetWindow)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.qGraphWidget)
        self.qTerminalWidget = QtWidgets.QDockWidget(MainWindow)
        self.qTerminalWidget.setObjectName("qTerminalWidget")
        self.qTerminalWidgetWindow = QtWidgets.QWidget()
        self.qTerminalWidgetWindow.setObjectName("qTerminalWidgetWindow")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.qTerminalWidgetWindow)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.qTrminalVLayout = QtWidgets.QVBoxLayout()
        self.qTrminalVLayout.setObjectName("qTrminalVLayout")
        self.qTerminalBrowser = QtWidgets.QTextBrowser(self.qTerminalWidgetWindow)
        self.qTerminalBrowser.setObjectName("qTerminalBrowser")
        self.qTrminalVLayout.addWidget(self.qTerminalBrowser)
        self.qTerminalHLayout = QtWidgets.QHBoxLayout()
        self.qTerminalHLayout.setObjectName("qTerminalHLayout")
        self.qTerminalLineEdit = QtWidgets.QLineEdit(self.qTerminalWidgetWindow)
        self.qTerminalLineEdit.setObjectName("qTerminalLineEdit")
        self.qTerminalHLayout.addWidget(self.qTerminalLineEdit)
        self.qTerminalSendButton = QtWidgets.QPushButton(self.qTerminalWidgetWindow)
        self.qTerminalSendButton.setObjectName("qTerminalSendButton")
        self.qTerminalHLayout.addWidget(self.qTerminalSendButton)
        self.qTrminalVLayout.addLayout(self.qTerminalHLayout)
        self.gridLayout_3.addLayout(self.qTrminalVLayout, 0, 0, 1, 1)
        self.qTerminalWidget.setWidget(self.qTerminalWidgetWindow)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.qTerminalWidget)
        self.qGraph2Widget = QtWidgets.QDockWidget(MainWindow)
        self.qGraph2Widget.setEnabled(True)
        self.qGraph2Widget.setFloating(False)
        self.qGraph2Widget.setObjectName("qGraph2Widget")
        self.qGraph2WidgetWondow = QtWidgets.QWidget()
        self.qGraph2WidgetWondow.setObjectName("qGraph2WidgetWondow")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.qGraph2WidgetWondow)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.qGraph2VLayout = QtWidgets.QVBoxLayout()
        self.qGraph2VLayout.setObjectName("qGraph2VLayout")
        self.verticalLayout_2.addLayout(self.qGraph2VLayout)
        self.qGraph2Widget.setWidget(self.qGraph2WidgetWondow)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.qGraph2Widget)
        self.actionSave_Data = QtWidgets.QAction(MainWindow)
        self.actionSave_Data.setObjectName("actionSave_Data")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.qActionConnectDevice = QtWidgets.QAction(MainWindow)
        self.qActionConnectDevice.setObjectName("qActionConnectDevice")
        self.qActionDisconnectDevice = QtWidgets.QAction(MainWindow)
        self.qActionDisconnectDevice.setObjectName("qActionDisconnectDevice")
        self.qActionCheckConnection = QtWidgets.QAction(MainWindow)
        self.qActionCheckConnection.setObjectName("qActionCheckConnection")
        self.qViewGraph = QtWidgets.QAction(MainWindow)
        self.qViewGraph.setCheckable(True)
        self.qViewGraph.setChecked(True)
        self.qViewGraph.setObjectName("qViewGraph")
        self.qViewTemp = QtWidgets.QAction(MainWindow)
        self.qViewTemp.setCheckable(True)
        self.qViewTemp.setChecked(True)
        self.qViewTemp.setObjectName("qViewTemp")
        self.qPeltierCurrent = QtWidgets.QAction(MainWindow)
        self.qPeltierCurrent.setCheckable(True)
        self.qPeltierCurrent.setChecked(True)
        self.qPeltierCurrent.setObjectName("qPeltierCurrent")
        self.actionGraph = QtWidgets.QAction(MainWindow)
        self.actionGraph.setObjectName("actionGraph")
        self.actionTempreture = QtWidgets.QAction(MainWindow)
        self.actionTempreture.setObjectName("actionTempreture")
        self.actionVoltage_Range = QtWidgets.QAction(MainWindow)
        self.actionVoltage_Range.setObjectName("actionVoltage_Range")
        self.actionCurent_Range = QtWidgets.QAction(MainWindow)
        self.actionCurent_Range.setObjectName("actionCurent_Range")
        self.actionDevice_Logger = QtWidgets.QAction(MainWindow)
        self.actionDevice_Logger.setObjectName("actionDevice_Logger")
        self.qViewTerminal = QtWidgets.QAction(MainWindow)
        self.qViewTerminal.setCheckable(True)
        self.qViewTerminal.setChecked(True)
        self.qViewTerminal.setObjectName("qViewTerminal")
        self.actionSecondary_Graph = QtWidgets.QAction(MainWindow)
        self.actionSecondary_Graph.setCheckable(True)
        self.actionSecondary_Graph.setChecked(True)
        self.actionSecondary_Graph.setObjectName("actionSecondary_Graph")
        self.actionManual_Control = QtWidgets.QAction(MainWindow)
        self.actionManual_Control.setCheckable(True)
        self.actionManual_Control.setChecked(True)
        self.actionManual_Control.setObjectName("actionManual_Control")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionDevice_Logger)
        self.menuDevice.addAction(self.qActionConnectDevice)
        self.menuDevice.addAction(self.qActionDisconnectDevice)
        self.menuDevice.addAction(self.qActionCheckConnection)
        self.menuView.addAction(self.qViewGraph)
        self.menuView.addAction(self.qViewTerminal)
        self.menuView.addAction(self.actionSecondary_Graph)
        self.menuView.addAction(self.actionManual_Control)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDevice.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.qMainTabWidget.setCurrentIndex(3)
        self.qDevADisplayComBox.setCurrentIndex(1)
        self.qPelADisplayComBox.setCurrentIndex(1)
        self.qTempMaxSpin.valueChanged['int'].connect(self.qTempMaxDial.setValue)
        self.qTempMaxDial.valueChanged['int'].connect(self.qTempMaxSpin.setValue)
        self.qTempStepDial.valueChanged['int'].connect(self.qTempStepSpin.setValue)
        self.qTempStepSpin.valueChanged['int'].connect(self.qTempStepDial.setValue)
        self.qTempMinSpin.valueChanged['int'].connect(self.qTempMinDial.setValue)
        self.qTempMinDial.valueChanged['int'].connect(self.qTempMinSpin.setValue)
        self.connect_GUI()
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Peltier & CHIL"))
        self.qTerminalSendCheckBox.setText(_translate("MainWindow", "Terminal Send"))
        self.qConnectionLabel.setText(_translate("MainWindow", "Not Connected"))
        self.qRawDisCheckBox.setText(_translate("MainWindow", "Raw Display"))
        self.qConstantLabelConst.setText(_translate("MainWindow", "Constant  :  "))
        self.qStartButton.setText(_translate("MainWindow", "Start"))
        self.qLabelRunTime.setText(_translate("MainWindow", "-- : -- : --"))
        self.qPauseButton.setText(_translate("MainWindow", "Pause"))
        self.qConstModeComBox.setItemText(0, _translate("MainWindow", "Temperature"))
        self.qConstModeComBox.setItemText(1, _translate("MainWindow", "Voltage"))
        self.qConstModeComBox.setItemText(2, _translate("MainWindow", "Current"))
        self.qConstLabelRun.setText(_translate("MainWindow", "Run Time  :  "))
        self.qConstLabelFile.setText(_translate("MainWindow", "File Name"))
        self.qStopButton.setText(_translate("MainWindow", "Stop"))
        self.qStaticLabelUnitT.setText(_translate("MainWindow", " Temperature Unit  :  "))
        self.qTemUnitComBox.setItemText(0, _translate("MainWindow", "°C"))
        self.qTemUnitComBox.setItemText(1, _translate("MainWindow", "K"))
        self.qStaticLabelTmax.setText(_translate("MainWindow", "Max"))
        self.qStaticLabelTMin.setText(_translate("MainWindow", "Min"))
        self.qStaticLabelTstep.setText(_translate("MainWindow", "Step"))
        self.qMainTabWidget.setTabText(self.qMainTabWidget.indexOf(self.qMainTempSetWidget), _translate("MainWindow", "Temperature"))
        self.qStaticLabelVmax.setText(_translate("MainWindow", "Max"))
        self.qStaticLabelVstep.setText(_translate("MainWindow", "Step"))
        self.qStaticLabelVMin.setText(_translate("MainWindow", "Min"))
        self.qVMaxUnitComBox.setItemText(0, _translate("MainWindow", "V"))
        self.qVMaxUnitComBox.setItemText(1, _translate("MainWindow", "mV"))
        self.qVMinUnitComBox.setItemText(0, _translate("MainWindow", "V"))
        self.qVMinUnitComBox.setItemText(1, _translate("MainWindow", "mV"))
        self.qVMaxUnitComBox_2.setItemText(0, _translate("MainWindow", "V"))
        self.qVMaxUnitComBox_2.setItemText(1, _translate("MainWindow", "mV"))
        self.qMainTabWidget.setTabText(self.qMainTabWidget.indexOf(self.qMainVoltSetWidget), _translate("MainWindow", "Voltage"))
        self.qStaticLabelIstep.setText(_translate("MainWindow", "Step"))
        self.qStaticLabelImax.setText(_translate("MainWindow", "Max"))
        self.qStaticLabelIMin.setText(_translate("MainWindow", "Min"))
        self.qStaticLabelPeltMax.setText(_translate("MainWindow", "Peltier (Max)"))
        self.qIStepUnitComBox.setItemText(0, _translate("MainWindow", "mA"))
        self.qIStepUnitComBox.setItemText(1, _translate("MainWindow", "A"))
        self.qIMinUnitComBox.setItemText(0, _translate("MainWindow", "mA"))
        self.qIMinUnitComBox.setItemText(1, _translate("MainWindow", "A"))
        self.qIMaxUnitComBox.setItemText(0, _translate("MainWindow", "mA"))
        self.qIMaxUnitComBox.setItemText(1, _translate("MainWindow", "A"))
        self.qStaticLabelA.setText(_translate("MainWindow", "A"))
        self.qMainTabWidget.setTabText(self.qMainTabWidget.indexOf(self.qMainCurrentSetWidget), _translate("MainWindow", "Current"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.qMainTabWidget.setTabText(self.qMainTabWidget.indexOf(self.qMainGraphSetWidget), _translate("MainWindow", "Graph"))
        self.qDevVDisplayComBox.setItemText(0, _translate("MainWindow", "mV"))
        self.qDevVDisplayComBox.setItemText(1, _translate("MainWindow", "V"))
        self.qDevVDisplayLabel.setText(_translate("MainWindow", "-"))
        self.qStaticLabelDevT.setText(_translate("MainWindow", "Device Temperature :"))
        self.qDevADisplayLabel.setText(_translate("MainWindow", "-"))
        self.qStaticLabelDevA.setText(_translate("MainWindow", "Device Current :"))
        self.qStaticLabelDdevV.setText(_translate("MainWindow", "Device Voltage :"))
        self.qDevADisplayComBox.setItemText(0, _translate("MainWindow", "μA"))
        self.qDevADisplayComBox.setItemText(1, _translate("MainWindow", "mA"))
        self.qDevADisplayComBox.setItemText(2, _translate("MainWindow", "A"))
        self.qStaticLabelPelA.setText(_translate("MainWindow", "Peltier Current :"))
        self.qPelADisplayComBox.setItemText(0, _translate("MainWindow", "mA"))
        self.qPelADisplayComBox.setItemText(1, _translate("MainWindow", "A"))
        self.qDevTDisplayComBox.setItemText(0, _translate("MainWindow", "°C"))
        self.qDevTDisplayComBox.setItemText(1, _translate("MainWindow", "K"))
        self.qPelADisplayLabel.setText(_translate("MainWindow", "-"))
        self.qDevTDisplayLabel.setText(_translate("MainWindow", "-"))
        self.qManPWMDApplyButton.setText(_translate("MainWindow", "Set Duty Cycle"))
        self.qStaticLabelPWMFreq.setText(_translate("MainWindow", "PWM Duty Cycle"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuDevice.setTitle(_translate("MainWindow", "Device"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.qGraphWidget.setWindowTitle(_translate("MainWindow", "Graph"))
        self.qTerminalWidget.setWindowTitle(_translate("MainWindow", "Device Terminal"))
        self.qTerminalSendButton.setText(_translate("MainWindow", "Send"))
        self.qGraph2Widget.setWindowTitle(_translate("MainWindow", "Time Graph"))
        self.actionSave_Data.setText(_translate("MainWindow", "Save Data"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.qActionConnectDevice.setText(_translate("MainWindow", "Connect Device"))
        self.qActionDisconnectDevice.setText(_translate("MainWindow", "Disconnect Device"))
        self.qActionCheckConnection.setText(_translate("MainWindow", "Check Connection"))
        self.qViewGraph.setText(_translate("MainWindow", "Graph"))
        self.qViewTemp.setText(_translate("MainWindow", "Tempreture"))
        self.qPeltierCurrent.setText(_translate("MainWindow", "Peltier Current"))
        self.actionGraph.setText(_translate("MainWindow", "Graph"))
        self.actionTempreture.setText(_translate("MainWindow", "Tempreture Range"))
        self.actionVoltage_Range.setText(_translate("MainWindow", "Voltage Range"))
        self.actionCurent_Range.setText(_translate("MainWindow", "Curent Range"))
        self.actionDevice_Logger.setText(_translate("MainWindow", "Device Logger"))
        self.qViewTerminal.setText(_translate("MainWindow", "Device Terminal"))
        self.actionSecondary_Graph.setText(_translate("MainWindow", "Secondary Graph"))
        self.actionManual_Control.setText(_translate("MainWindow", "Manual Control"))

    def connect_GUI(self):
        #self.qStartButton.clicked.connect(self.start_button_pressed)
        #self.qStopButton.clicked.connect(self.stop_button_pressed)
        #self.qPauseButton.clicked.connect(self.pause_button_pressed)
        self.qViewGraph.toggled.connect(self.qGraphWidget.setVisible)
        self.qGraphWidget.visibilityChanged.connect(self.qViewGraph.setChecked)
        self.qViewTerminal.toggled.connect(self.qTerminalWidget.setVisible)
        self.qTerminalWidget.visibilityChanged.connect(self.qViewTerminal.setChecked)
        self.fetch_thread = QtCore.QThread()
        self.device_connected = False
        self.qActionConnectDevice.triggered.connect(self.connect_device)
        self.qManPWMDApplyButton.clicked.connect(self.sendManualPWMDValue)
        self.setup_graph_widget()
        
    def setup_graph_widget(self):
        self.graph_canvas = GraphCanvas(parent = self.qGraphWidgetWindow)
        self.qGraphVLayout.addWidget(self.graph_canvas)
        self.qGraphWidget.toolbar = NavigationToolbar(self.graph_canvas, 
                self.qGraphWidgetWindow)
     
    def sendManualPWMDValue(self):
        pwm_d = self.qManPWMDSpinBox.value()
        send_msg = [INSTR_PACKET_START, SET_PELT_VOLTAGE, pwm_d >> 8, pwm_d & 0xff, INSTR_PACKET_END]
        self.send_to_device(send_msg)
        self.device_terminal_write(str(send_msg),SUCCESS)
        
    def send_to_device(self, data):
        if(self.device_connected):
            data.append(len(data))
            message = bytes(data)
            self.tivaC.send_data(message)
        
    
    def connect_device(self):
        if self.device_connected:
            if self.tivaC.connected:
                self.qButtonSend.clicked.disconnect(self.send_data)
                self.tivaC.disconnect_device()
                del self.tivaC
                self.device_connected = False
                self.device_terminal_write("Tive C disconnected",FAILURE)
                self.qConnectionLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
                    "background-color: rgb(255, 0, 0);\n"
                    "border-color: rgb(255, 255, 255);")
                self.qConnectionLabel.setText("Disconnected")
        else:
            self.device_terminal_write("Attempting to connect ..")
            self.tivaC = USB_device(idVendor = 0x1cbe, idProduct = 0x0003)
            for retry in range(0,5):
                connected = self.tivaC.connect_device()
                if connected:
                    self.tivaC.moveToThread(self.fetch_thread)
                    self.tivaC.dataReceived.connect(self.handle_data)
                    self.fetch_thread.started.connect(self.tivaC.read_loop)
                    self.fetch_thread.start()
                    self.device_terminal_write("TIva C connected",SUCCESS)
                    self.qConnectionLabel.setStyleSheet("color: rgb(0, 0, 0);\n"
                        "background-color: rgb(0,255, 0);\n"
                        "border-color: rgb(0, 0, 0);")
                    self.qConnectionLabel.setText("Connected")
                    self.device_connected = True
                    break
                else:
                    self.device_terminal_write("Retrying ("+str(retry)+"/4)",NORMAL)
            if not self.tivaC.connected:
                self.device_terminal_write("Unable to connect",FAILURE)
    
    def handle_data(self,data):
        if self.tivaC.mutex.tryLock():
            new_data = [byte for byte in data]
            self.tivaC.primaryBuff = []
            #print("print\n"+str(self.tivaC.primaryBuff))
            self.tivaC.mutex.unlock()
            #processed_data = [chr(new_data[i]) for i in range(len(new_data))]
            #self.device_terminal_write(" ".join(new_data))
            self.device_terminal_write(" ".join(str(hex(ord(i))) for i in new_data))
            message = [ord(i) for i in new_data]
            if(len(message) != message[-1]):
                message = []
                self.device_terminal_write("Currupt Packet",ATTENTION)
                #self.device_terminal_write(" ".join(str(hex(ord(i))) for i in new_data))
            else:
                self.decoded_msg = process_message(message)
                self.received_msg_fields  = self.decoded_msg.keys() 
                self.take_actions()
                self.update_GUI()
    
    """
    All Controlling functions
    """
    def take_actions(self):
        pass
    """
    All GUI update function
    """    
    def update_GUI(self):
        terminal_msg = "New Message"
        curr_display = ['--','--','--','--']
        if "Pelt_Voltage" in self.received_msg_fields :
            pass
        if "Pelt_Curr" in self.received_msg_fields :
            curr_display[2] = self.decoded_msg["Pelt_Curr"]
        self.update_curr_display_parameters(curr_display)
        self.device_terminal_write(terminal_msg,NORMAL)
        
    def device_terminal_write(self,message,type = NORMAL):
        self.qTerminalBrowser.append(type+message+"</font>\n")
    
    """ 
    Update Display Values on main screen
    3. Device Voltage  2. Device Current 1. Peltier Current 0. Current Temperature
    """    
    def update_curr_display_parameters(self, value_list):
        self.qDevVDisplayLabel.setText(str(value_list[0]))
        self.qDevADisplayLabel.setText(str(value_list[1]))
        self.qPelADisplayLabel.setText(str(value_list[2]))
        self.qDevTDisplayLabel.setText(str(value_list[3]))
        
    def update_graph():
        pass
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

