from defines import *
from graph_canvas import *
#------------------------------------------------------------------------------#
class Ui_MainWindow(object):
    #--------------------------------------------------------------------------#
    # Setup UI (AutoGen)
    # Call This in other window to setup as Child Window.
    #--------------------------------------------------------------------------#
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(723, 534)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.qMainWindow = QtWidgets.QWidget(MainWindow)
        self.qMainWindow.setObjectName("qMainWindow")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.qMainWindow)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.qMainWindowGLayout1 = QtWidgets.QGridLayout()
        self.qMainWindowGLayout1.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.qMainWindowGLayout1.setObjectName("qMainWindowGLayout1")
        self.qStartButton = QtWidgets.QPushButton(self.qMainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qStartButton.sizePolicy().hasHeightForWidth())
        self.qStartButton.setSizePolicy(sizePolicy)
        self.qStartButton.setMinimumSize(QtCore.QSize(100, 0))
        self.qStartButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.qStartButton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 255, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.qStartButton.setObjectName("qStartButton")
        self.qMainWindowGLayout1.addWidget(self.qStartButton, 3, 2, 1, 1)
        self.qConstantLabelConst = QtWidgets.QLabel(self.qMainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qConstantLabelConst.sizePolicy().hasHeightForWidth())
        self.qConstantLabelConst.setSizePolicy(sizePolicy)
        self.qConstantLabelConst.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.qConstantLabelConst.setObjectName("qConstantLabelConst")
        self.qMainWindowGLayout1.addWidget(self.qConstantLabelConst, 0, 1, 1, 1)
        self.qConstModeComBox = QtWidgets.QComboBox(self.qMainWindow)
        self.qConstModeComBox.setObjectName("qConstModeComBox")
        self.qConstModeComBox.addItem("")
        self.qConstModeComBox.addItem("")
        self.qConstModeComBox.addItem("")
        self.qMainWindowGLayout1.addWidget(self.qConstModeComBox, 0, 2, 1, 1)
        self.qFileNameLineEdi = QtWidgets.QLineEdit(self.qMainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qFileNameLineEdi.sizePolicy().hasHeightForWidth())
        self.qFileNameLineEdi.setSizePolicy(sizePolicy)
        self.qFileNameLineEdi.setObjectName("qFileNameLineEdi")
        self.qMainWindowGLayout1.addWidget(self.qFileNameLineEdi, 2, 1, 1, 1)
        self.qPauseButton = QtWidgets.QPushButton(self.qMainWindow)
        self.qPauseButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qPauseButton.sizePolicy().hasHeightForWidth())
        self.qPauseButton.setSizePolicy(sizePolicy)
        self.qPauseButton.setMinimumSize(QtCore.QSize(100, 0))
        self.qPauseButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.qPauseButton.setMouseTracking(False)
        self.qPauseButton.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.qPauseButton.setObjectName("qPauseButton")
        self.qMainWindowGLayout1.addWidget(self.qPauseButton, 3, 1, 1, 1)
        self.qLabelRunTime = QtWidgets.QLabel(self.qMainWindow)
        self.qLabelRunTime.setMinimumSize(QtCore.QSize(100, 0))
        self.qLabelRunTime.setMaximumSize(QtCore.QSize(200, 16777215))
        self.qLabelRunTime.setObjectName("qLabelRunTime")
        self.qMainWindowGLayout1.addWidget(self.qLabelRunTime, 1, 2, 1, 1)
        self.qConstLabelFile = QtWidgets.QLabel(self.qMainWindow)
        self.qConstLabelFile.setMaximumSize(QtCore.QSize(200, 16777215))
        self.qConstLabelFile.setObjectName("qConstLabelFile")
        self.qMainWindowGLayout1.addWidget(self.qConstLabelFile, 2, 2, 1, 1)
        self.qConstLabelRun = QtWidgets.QLabel(self.qMainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qConstLabelRun.sizePolicy().hasHeightForWidth())
        self.qConstLabelRun.setSizePolicy(sizePolicy)
        self.qConstLabelRun.setObjectName("qConstLabelRun")
        self.qMainWindowGLayout1.addWidget(self.qConstLabelRun, 1, 1, 1, 1)
        self.qStopButton = QtWidgets.QPushButton(self.qMainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qStopButton.sizePolicy().hasHeightForWidth())
        self.qStopButton.setSizePolicy(sizePolicy)
        self.qStopButton.setMinimumSize(QtCore.QSize(110, 0))
        self.qStopButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.qStopButton.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);")
        self.qStopButton.setObjectName("qStopButton")
        self.qMainWindowGLayout1.addWidget(self.qStopButton, 3, 0, 1, 1)
        self.gridLayout_2.addLayout(self.qMainWindowGLayout1, 4, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.qMainWindow)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 3, 0, 1, 1)
        self.qMainWindowVLayout1 = QtWidgets.QVBoxLayout()
        self.qMainWindowVLayout1.setObjectName("qMainWindowVLayout1")
        self.qMainTabWidget = QtWidgets.QTabWidget(self.qMainWindow)
        self.qMainTabWidget.setMinimumSize(QtCore.QSize(300, 200))
        self.qMainTabWidget.setMaximumSize(QtCore.QSize(400, 16777215))
        self.qMainTabWidget.setObjectName("qMainTabWidget")
        self.qMainTempSetWidget_2 = QtWidgets.QWidget()
        self.qMainTempSetWidget_2.setObjectName("qMainTempSetWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.qMainTempSetWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.qMainTabWidget.addTab(self.qMainTempSetWidget_2, "")
        self.qMainVoltSetWidget = QtWidgets.QWidget()
        self.qMainVoltSetWidget.setObjectName("qMainVoltSetWidget")
        self.qMainTabWidget.addTab(self.qMainVoltSetWidget, "")
        self.qMainCurrentSetWidget = QtWidgets.QWidget()
        self.qMainCurrentSetWidget.setObjectName("qMainCurrentSetWidget")
        self.qMainTabWidget.addTab(self.qMainCurrentSetWidget, "")
        self.qMainGraphSetWidget = QtWidgets.QWidget()
        self.qMainGraphSetWidget.setObjectName("qMainGraphSetWidget")
        self.qMainTabWidget.addTab(self.qMainGraphSetWidget, "")
        self.qMainWindowVLayout1.addWidget(self.qMainTabWidget)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.qDevVDisplayComBox = QtWidgets.QComboBox(self.qMainWindow)
        self.qDevVDisplayComBox.setMinimumSize(QtCore.QSize(50, 0))
        self.qDevVDisplayComBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.qDevVDisplayComBox.setObjectName("qDevVDisplayComBox")
        self.qDevVDisplayComBox.addItem("")
        self.qDevVDisplayComBox.addItem("")
        self.gridLayout_4.addWidget(self.qDevVDisplayComBox, 0, 2, 1, 1)
        self.qDevVDisplayLabel = QtWidgets.QLabel(self.qMainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qDevVDisplayLabel.sizePolicy().hasHeightForWidth())
        self.qDevVDisplayLabel.setSizePolicy(sizePolicy)
        self.qDevVDisplayLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.qDevVDisplayLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.qDevVDisplayLabel.setBaseSize(QtCore.QSize(150, 0))
        self.qDevVDisplayLabel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.qDevVDisplayLabel.setObjectName("qDevVDisplayLabel")
        self.gridLayout_4.addWidget(self.qDevVDisplayLabel, 0, 1, 1, 1)
        self.qStaticLabelDevT = QtWidgets.QLabel(self.qMainWindow)
        self.qStaticLabelDevT.setObjectName("qStaticLabelDevT")
        self.gridLayout_4.addWidget(self.qStaticLabelDevT, 3, 0, 1, 1)
        self.qDevADisplayLabel = QtWidgets.QLabel(self.qMainWindow)
        self.qDevADisplayLabel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.qDevADisplayLabel.setObjectName("qDevADisplayLabel")
        self.gridLayout_4.addWidget(self.qDevADisplayLabel, 1, 1, 1, 1)
        self.qStaticLabelDevA = QtWidgets.QLabel(self.qMainWindow)
        self.qStaticLabelDevA.setObjectName("qStaticLabelDevA")
        self.gridLayout_4.addWidget(self.qStaticLabelDevA, 1, 0, 1, 1)
        self.qStaticLabelDdevV = QtWidgets.QLabel(self.qMainWindow)
        self.qStaticLabelDdevV.setMinimumSize(QtCore.QSize(100, 0))
        self.qStaticLabelDdevV.setMaximumSize(QtCore.QSize(200, 16777215))
        self.qStaticLabelDdevV.setObjectName("qStaticLabelDdevV")
        self.gridLayout_4.addWidget(self.qStaticLabelDdevV, 0, 0, 1, 1)
        self.qDevADisplayComBox = QtWidgets.QComboBox(self.qMainWindow)
        self.qDevADisplayComBox.setMinimumSize(QtCore.QSize(50, 0))
        self.qDevADisplayComBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.qDevADisplayComBox.setObjectName("qDevADisplayComBox")
        self.qDevADisplayComBox.addItem("")
        self.qDevADisplayComBox.addItem("")
        self.qDevADisplayComBox.addItem("")
        self.gridLayout_4.addWidget(self.qDevADisplayComBox, 1, 2, 1, 1)
        self.qStaticLabelPelA = QtWidgets.QLabel(self.qMainWindow)
        self.qStaticLabelPelA.setObjectName("qStaticLabelPelA")
        self.gridLayout_4.addWidget(self.qStaticLabelPelA, 2, 0, 1, 1)
        self.qPelADisplayComBox = QtWidgets.QComboBox(self.qMainWindow)
        self.qPelADisplayComBox.setMinimumSize(QtCore.QSize(50, 0))
        self.qPelADisplayComBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.qPelADisplayComBox.setObjectName("qPelADisplayComBox")
        self.qPelADisplayComBox.addItem("")
        self.qPelADisplayComBox.addItem("")
        self.gridLayout_4.addWidget(self.qPelADisplayComBox, 2, 2, 1, 1)
        self.qDevTDisplayComBox = QtWidgets.QComboBox(self.qMainWindow)
        self.qDevTDisplayComBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.qDevTDisplayComBox.setObjectName("qDevTDisplayComBox")
        self.qDevTDisplayComBox.addItem("")
        self.qDevTDisplayComBox.addItem("")
        self.qDevTDisplayComBox.addItem("")
        self.gridLayout_4.addWidget(self.qDevTDisplayComBox, 3, 2, 1, 1)
        self.qPelADisplayLabel = QtWidgets.QLabel(self.qMainWindow)
        self.qPelADisplayLabel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.qPelADisplayLabel.setObjectName("qPelADisplayLabel")
        self.gridLayout_4.addWidget(self.qPelADisplayLabel, 2, 1, 1, 1)
        self.qDevTDisplayLabel = QtWidgets.QLabel(self.qMainWindow)
        self.qDevTDisplayLabel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.qDevTDisplayLabel.setObjectName("qDevTDisplayLabel")
        self.gridLayout_4.addWidget(self.qDevTDisplayLabel, 3, 1, 1, 1)
        self.qMainWindowVLayout1.addLayout(self.gridLayout_4)
        self.gridLayout_2.addLayout(self.qMainWindowVLayout1, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.qMainWindow)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 723, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuDevice = QtWidgets.QMenu(self.menubar)
        self.menuDevice.setObjectName("menuDevice")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.qGraphWidget = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qGraphWidget.sizePolicy().hasHeightForWidth())
        self.qGraphWidget.setSizePolicy(sizePolicy)
        self.qGraphWidget.setBaseSize(QtCore.QSize(463, 300))
        self.qGraphWidget.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.qGraphWidget.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.qGraphWidget.setObjectName("qGraphWidget")
        self.qGraphWidgetWindow = QtWidgets.QWidget()
        self.qGraphWidgetWindow.setObjectName("qGraphWidgetWindow")
        self.gridLayout = QtWidgets.QGridLayout(self.qGraphWidgetWindow)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.qGraphVLayout = QtWidgets.QVBoxLayout()
        self.qGraphVLayout.setObjectName("qGraphVLayout")
        self.gridLayout.addLayout(self.qGraphVLayout, 0, 1, 1, 1)
        self.qGraphWidget.setWidget(self.qGraphWidgetWindow)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.qGraphWidget)
        self.qTerminalWidget = QtWidgets.QDockWidget(MainWindow)
        self.qTerminalWidget.setObjectName("qTerminalWidget")
        self.qTerminalWidgetWindow = QtWidgets.QWidget()
        self.qTerminalWidgetWindow.setObjectName("qTerminalWidgetWindow")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.qTerminalWidgetWindow)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.qTrminalVLayout = QtWidgets.QVBoxLayout()
        self.qTrminalVLayout.setObjectName("qTrminalVLayout")
        self.qTerminalBrowser = QtWidgets.QTextBrowser(self.qTerminalWidgetWindow)
        self.qTerminalBrowser.setObjectName("qTerminalBrowser")
        self.qTrminalVLayout.addWidget(self.qTerminalBrowser)
        self.qTerminalHLayout = QtWidgets.QHBoxLayout()
        self.qTerminalHLayout.setObjectName("qTerminalHLayout")
        self.qTerminalLineEdit = QtWidgets.QLineEdit(self.qTerminalWidgetWindow)
        self.qTerminalLineEdit.setObjectName("qTerminalLineEdit")
        self.qTerminalHLayout.addWidget(self.qTerminalLineEdit)
        self.qTerminalSendButton = QtWidgets.QPushButton(self.qTerminalWidgetWindow)
        self.qTerminalSendButton.setObjectName("qTerminalSendButton")
        self.qTerminalHLayout.addWidget(self.qTerminalSendButton)
        self.qTrminalVLayout.addLayout(self.qTerminalHLayout)
        self.gridLayout_3.addLayout(self.qTrminalVLayout, 0, 0, 1, 1)
        self.qTerminalWidget.setWidget(self.qTerminalWidgetWindow)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.qTerminalWidget)
        self.actionSave_Data = QtWidgets.QAction(MainWindow)
        self.actionSave_Data.setObjectName("actionSave_Data")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.qActionConnectDevice = QtWidgets.QAction(MainWindow)
        self.qActionConnectDevice.setObjectName("qActionConnectDevice")
        self.qActionDisconnectDevice = QtWidgets.QAction(MainWindow)
        self.qActionDisconnectDevice.setObjectName("qActionDisconnectDevice")
        self.qActionCheckConnection = QtWidgets.QAction(MainWindow)
        self.qActionCheckConnection.setObjectName("qActionCheckConnection")
        self.qViewGraph = QtWidgets.QAction(MainWindow)
        self.qViewGraph.setCheckable(True)
        self.qViewGraph.setChecked(True)
        self.qViewGraph.setObjectName("qViewGraph")
        self.qViewTemp = QtWidgets.QAction(MainWindow)
        self.qViewTemp.setCheckable(True)
        self.qViewTemp.setChecked(True)
        self.qViewTemp.setObjectName("qViewTemp")
        self.qPeltierCurrent = QtWidgets.QAction(MainWindow)
        self.qPeltierCurrent.setCheckable(True)
        self.qPeltierCurrent.setChecked(True)
        self.qPeltierCurrent.setObjectName("qPeltierCurrent")
        self.actionGraph = QtWidgets.QAction(MainWindow)
        self.actionGraph.setObjectName("actionGraph")
        self.actionTempreture = QtWidgets.QAction(MainWindow)
        self.actionTempreture.setObjectName("actionTempreture")
        self.actionVoltage_Range = QtWidgets.QAction(MainWindow)
        self.actionVoltage_Range.setObjectName("actionVoltage_Range")
        self.actionCurent_Range = QtWidgets.QAction(MainWindow)
        self.actionCurent_Range.setObjectName("actionCurent_Range")
        self.actionDevice_Logger = QtWidgets.QAction(MainWindow)
        self.actionDevice_Logger.setObjectName("actionDevice_Logger")
        self.qViewTerminal = QtWidgets.QAction(MainWindow)
        self.qViewTerminal.setCheckable(True)
        self.qViewTerminal.setChecked(True)
        self.qViewTerminal.setObjectName("qViewTerminal")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionDevice_Logger)
        self.menuDevice.addAction(self.qActionConnectDevice)
        self.menuDevice.addAction(self.qActionDisconnectDevice)
        self.menuDevice.addAction(self.qActionCheckConnection)
        self.menuView.addAction(self.qViewGraph)
        self.menuView.addAction(self.qViewTerminal)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDevice.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.connect_handles()
        self.qMainTabWidget.setCurrentIndex(0)
        self.qDevADisplayComBox.setCurrentIndex(1)
        self.qPelADisplayComBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    #--------------------------------------------------------------------------#
    # Translate UI (AutoGen)
    #--------------------------------------------------------------------------#
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Peltier & CHIL"))
        self.qStartButton.setText(_translate("MainWindow", "Start"))
        self.qConstantLabelConst.setText(_translate("MainWindow", "Constant"))
        self.qConstModeComBox.setItemText(0, _translate("MainWindow", "Temperature"))
        self.qConstModeComBox.setItemText(1, _translate("MainWindow", "Voltage"))
        self.qConstModeComBox.setItemText(2, _translate("MainWindow", "Current"))
        self.qPauseButton.setText(_translate("MainWindow", "Pause"))
        self.qLabelRunTime.setText(_translate("MainWindow", "-- : -- : --"))
        self.qConstLabelFile.setText(_translate("MainWindow", "File Name"))
        self.qConstLabelRun.setText(_translate("MainWindow", "Run Time"))
        self.qStopButton.setText(_translate("MainWindow", "Stop"))
        self.qMainTabWidget.setTabText(self.qMainTabWidget.indexOf(self.qMainTempSetWidget_2), _translate("MainWindow", "Temperature"))
        self.qMainTabWidget.setTabText(self.qMainTabWidget.indexOf(self.qMainVoltSetWidget), _translate("MainWindow", "Voltage"))
        self.qMainTabWidget.setTabText(self.qMainTabWidget.indexOf(self.qMainCurrentSetWidget), _translate("MainWindow", "Current"))
        self.qMainTabWidget.setTabText(self.qMainTabWidget.indexOf(self.qMainGraphSetWidget), _translate("MainWindow", "Graph"))
        self.qDevVDisplayComBox.setItemText(0, _translate("MainWindow", "mV"))
        self.qDevVDisplayComBox.setItemText(1, _translate("MainWindow", "V"))
        self.qDevVDisplayLabel.setText(_translate("MainWindow", "-"))
        self.qStaticLabelDevT.setText(_translate("MainWindow", "Device Temperature :"))
        self.qDevADisplayLabel.setText(_translate("MainWindow", "-"))
        self.qStaticLabelDevA.setText(_translate("MainWindow", "Device Current :"))
        self.qStaticLabelDdevV.setText(_translate("MainWindow", "Device Voltage :"))
        self.qDevADisplayComBox.setItemText(0, _translate("MainWindow", "μA"))
        self.qDevADisplayComBox.setItemText(1, _translate("MainWindow", "mA"))
        self.qDevADisplayComBox.setItemText(2, _translate("MainWindow", "A"))
        self.qStaticLabelPelA.setText(_translate("MainWindow", "Peltier Current :"))
        self.qPelADisplayComBox.setItemText(0, _translate("MainWindow", "mA"))
        self.qPelADisplayComBox.setItemText(1, _translate("MainWindow", "A"))
        self.qDevTDisplayComBox.setItemText(0, _translate("MainWindow", "°C"))
        self.qDevTDisplayComBox.setItemText(1, _translate("MainWindow", "°F"))
        self.qDevTDisplayComBox.setItemText(2, _translate("MainWindow", "K"))
        self.qPelADisplayLabel.setText(_translate("MainWindow", "-"))
        self.qDevTDisplayLabel.setText(_translate("MainWindow", "-"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuDevice.setTitle(_translate("MainWindow", "Device"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.qGraphWidget.setWindowTitle(_translate("MainWindow", "Graph"))
        self.qTerminalWidget.setWindowTitle(_translate("MainWindow", "Device Terminal"))
        self.qTerminalSendButton.setText(_translate("MainWindow", "Send"))
        self.actionSave_Data.setText(_translate("MainWindow", "Save Data"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.qActionConnectDevice.setText(_translate("MainWindow", "Connect Device"))
        self.qActionDisconnectDevice.setText(_translate("MainWindow", "Disconnect Device"))
        self.qActionCheckConnection.setText(_translate("MainWindow", "Check Connection"))
        self.qViewGraph.setText(_translate("MainWindow", "Graph"))
        self.qViewTemp.setText(_translate("MainWindow", "Tempreture"))
        self.qPeltierCurrent.setText(_translate("MainWindow", "Peltier Current"))
        self.actionGraph.setText(_translate("MainWindow", "Graph"))
        self.actionTempreture.setText(_translate("MainWindow", "Tempreture Range"))
        self.actionVoltage_Range.setText(_translate("MainWindow", "Voltage Range"))
        self.actionCurent_Range.setText(_translate("MainWindow", "Curent Range"))
        self.actionDevice_Logger.setText(_translate("MainWindow", "Device Logger"))
        self.qViewTerminal.setText(_translate("MainWindow", "Device Terminal"))



    """-------------------------------------------------------------------------
    Setup UI handles
    .....................
    Tasks
    -----
    1. Connect view device terminal and graph to menubar acions
    2. Connect start, stop, pause buttons signals to corresponding functions
    3. Connect Send to slot
    4. Connect/Disconnect Device to slots
    5. Check connections to slot
    6. Setup Grapg Widget
    
    ------------------------------------------------------------------------#"""
    def connect_handles(self):
        #self.qStartButton.clicked.connect(self.start_button_pressed)
        #self.qStopButton.clicked.connect(self.stop_button_pressed)
        #self.qPauseButton.clicked.connect(self.pause_button_pressed)
        self.qViewGraph.toggled.connect(self.qGraphWidget.setVisible)
        self.qGraphWidget.visibilityChanged.connect(self.qViewGraph.setChecked)
        self.qViewTerminal.toggled.connect(self.qTerminalWidget.setVisible)
        self.qTerminalWidget.visibilityChanged.connect(self.qViewTerminal.setChecked)
        self.setup_graph_widget()
        
    def setup_graph_widget(self):
        self.graph_canvas = GraphCanvas(parent = self.qGraphWidgetWindow)
        self.qGraphVLayout.addWidget(self.graph_canvas)
        self.qGraphWidget.toolbar = NavigationToolbar(self.graph_canvas, 
                self.qGraphWidgetWindow)
                
    def start_button_pressed(self):
        
#------------------------------------------------------------------------------#
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

